name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       # Paso 1: Checkout del c√≥digo del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install build-essential -y

      - name: Compile C code
        run: gcc -o mi_programa challenge07/starter.c
        
      - name: Run the compiled program
        run: ./mi_programa
